version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html  # Monta el código de Laravel en el contenedor
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf  # Configuración de Apache
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public  # Cambia el directorio raíz de Apache
    networks:
      - laravel_network
    command: ["/usr/local/bin/init.sh"]  # Cambia la ruta al script

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - laravel_network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
